name: Build Zig programs

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo DEBIAN_FRONTEND=noninteractive apt -y install build-essential gcc curl
          curl -LO https://ziglang.org/download/0.14.0/zig-linux-x86_64-0.14.0.tar.xz
          tar -xvf zig-linux-x86_64-0.14.0.tar.xz
          echo "${{ github.workspace }}/zig-linux-x86_64-0.14.0" >> $GITHUB_PATH

      - name: Build the Zig hello world
        run: |
          cd zig
          zig build-exe -isystem . example.zig
